apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: ares-backend-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /api/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: backend-service
              port:
                number: {{.Values.backend.service.port}}