apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  replicas: {{.Values.mongodb.replicaCount}}
  serviceName: mongodb-service
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{.Values.mongodb.image.repository}}:{{.Values.mongodb.image.tag}}"
          ports:
            - containerPort: {{.Values.mongodb.service.port}}
          volumeMounts:
            - name: mongodb-data
              mountPath: {{.Values.mongodb.persistence.mountPath}}
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: 
          - {{.Values.mongodb.persistence.accessMode}}
        resources:
          requests:
            storage: {{.Values.mongodb.persistence.size}}
